name: Continuous build and release docker image
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          pip install tests/
          pytest tests/
  main:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: timo-reymann/docker-semantic-release-gh-action@v1
        with:
          image: timoreymann/chrooted-ftp
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
